export const CABA_CENTER: [number, number] = [-34.6037, -58.3816];

export const BARRIOS_CABA = [
  "Agronomía",
  "Almagro",
  "Balvanera",
  "Barracas",
  "Belgrano",
  "Boedo",
  "Caballito",
  "Chacarita",
  "Coghlan",
  "Colegiales",
  "Constitución",
  "Flores",
  "Floresta",
  "La Boca",
  "La Paternal",
  "Liniers",
  "Mataderos",
  "Monte Castro",
  "Monserrat",
  "Nueva Pompeya",
  "Núñez",
  "Palermo",
  "Parque Avellaneda",
  "Parque Chacabuco",
  "Parque Chas",
  "Parque Patricios",
  "Puerto Madero",
  "Recoleta",
  "Retiro",
  "Saavedra",
  "San Cristóbal",
  "San Nicolás",
  "San Telmo",
  "Vélez Sársfield",
  "Versalles",
  "Villa Crespo",
  "Villa del Parque",
  "Villa Devoto",
  "Villa General Mitre",
  "Villa Lugano",
  "Villa Luro",
  "Villa Ortúzar",
  "Villa Pueyrredón",
  "Villa Real",
  "Villa Riachuelo",
  "Villa Santa Rita",
  "Villa Soldati",
  "Villa Urquiza",
] as const;

export const RAZAS_COMUNES = [
  "Mestizo / Sin raza definida",
  "Caniche",
  "Labrador",
  "Golden Retriever",
  "Pastor Alemán",
  "Bulldog Francés",
  "Bulldog Inglés",
  "Chihuahua",
  "Yorkshire Terrier",
  "Schnauzer",
  "Pug",
  "Beagle",
  "Boxer",
  "Border Collie",
  "Cocker Spaniel",
  "Dálmata",
  "Husky Siberiano",
  "Pitbull",
  "Rottweiler",
  "Salchicha (Dachshund)",
  "Otro",
] as const;

export const COLORES_COMUNES = [
  "Negro",
  "Blanco",
  "Marrón",
  "Marrón claro",
  "Marrón oscuro",
  "Beige",
  "Dorado",
  "Gris",
  "Atigrado",
  "Bicolor",
  "Tricolor",
  "Manchado",
] as const;

export const ESTADO_LABELS = {
  perdido: { texto: "Perdido", emoji: "🔴", color: "bg-red-100 text-red-800 border-red-200" },
  avistado: { texto: "Avistado", emoji: "🟡", color: "bg-yellow-100 text-yellow-800 border-yellow-200" },
  reunido: { texto: "Reunido", emoji: "🟢", color: "bg-green-100 text-green-800 border-green-200" },
} as const;

export const TAMANO_LABELS = {
  pequeno: "Pequeño (hasta 10kg)",
  mediano: "Mediano (10-25kg)",
  grande: "Grande (más de 25kg)",
} as const;
