import type { Publicacion } from "./types";

export const PUBLICACIONES_MOCK: Publicacion[] = [
  {
    id: "pub-001",
    tipo: "perdido",
    estado: "perdido",
    perro: {
      nombre: "Toto",
      raza: "Caniche",
      color: "Blanco",
      tamano: "pequeno",
      sexo: "macho",
      edadAproximada: "5 años",
      descripcion: "Muy cariñoso, responde a su nombre. Tiene una mancha gris en la oreja izquierda.",
      caracteristicasUnicas: "Collar rojo con chapita dorada con número de teléfono",
    },
    ubicacion: {
      lat: -34.5875,
      lng: -58.4205,
      barrio: "Palermo",
      direccionAproximada: "Plaza Italia y alrededores",
    },
    fechaEvento: "2026-05-19",
    fechaPublicacion: "2026-05-19T22:30:00",
    fotos: ["https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=600"],
    contacto: {
      nombre: "María González",
      telefono: "+5491156789012",
      preferenciaContacto: "whatsapp",
    },
    recompensa: 50000,
    pistas: [],
  },
  {
    id: "pub-002",
    tipo: "perdido",
    estado: "avistado",
    perro: {
      nombre: "Luna",
      raza: "Labrador",
      color: "Dorado",
      tamano: "grande",
      sexo: "hembra",
      edadAproximada: "3 años",
      descripcion: "Muy tímida con extraños pero amigable. Tiene la cola un poco curvada.",
      caracteristicasUnicas: "Pañuelo azul al cuello",
    },
    ubicacion: {
      lat: -34.6118,
      lng: -58.3960,
      barrio: "Recoleta",
      direccionAproximada: "Cementerio de Recoleta",
    },
    fechaEvento: "2026-05-17",
    fechaPublicacion: "2026-05-17T18:00:00",
    fotos: ["https://images.unsplash.com/photo-1552053831-71594a27632d?w=600"],
    contacto: {
      nombre: "Carlos Méndez",
      telefono: "+5491145678901",
      email: "carlos.mendez@example.com",
      preferenciaContacto: "telefono",
    },
    pistas: [
      {
        id: "pista-001",
        publicacionId: "pub-002",
        autorNombre: "Vecina anónima",
        mensaje: "La vi ayer a la tarde cerca de Av. Las Heras y Pueyrredón, parecía perdida.",
        fecha: "2026-05-21T15:00:00",
      },
    ],
  },
  {
    id: "pub-003",
    tipo: "encontrado",
    estado: "perdido",
    perro: {
      raza: "Mestizo / Sin raza definida",
      color: "Marrón claro",
      tamano: "mediano",
      sexo: "macho",
      edadAproximada: "Adulto",
      descripcion: "Lo encontré dando vueltas asustado. Es muy bueno. Lo tengo en mi casa hasta encontrar a su familia.",
      caracteristicasUnicas: "Tiene una cicatriz pequeña sobre el ojo derecho",
    },
    ubicacion: {
      lat: -34.6280,
      lng: -58.4145,
      barrio: "Caballito",
      direccionAproximada: "Parque Rivadavia",
    },
    fechaEvento: "2026-05-20",
    fechaPublicacion: "2026-05-20T09:15:00",
    fotos: ["https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600"],
    contacto: {
      nombre: "Lucía Fernández",
      telefono: "+5491134567890",
      preferenciaContacto: "whatsapp",
    },
    pistas: [],
  },
  {
    id: "pub-004",
    tipo: "perdido",
    estado: "reunido",
    perro: {
      nombre: "Roco",
      raza: "Beagle",
      color: "Tricolor",
      tamano: "mediano",
      sexo: "macho",
      edadAproximada: "2 años",
      descripcion: "Se escapó por un portón abierto. Muy juguetón.",
    },
    ubicacion: {
      lat: -34.5727,
      lng: -58.4334,
      barrio: "Belgrano",
      direccionAproximada: "Av. Cabildo y Juramento",
    },
    fechaEvento: "2026-05-10",
    fechaPublicacion: "2026-05-10T14:00:00",
    fotos: ["https://images.unsplash.com/photo-1505628346881-b72b27e84530?w=600"],
    contacto: {
      nombre: "Diego Romero",
      telefono: "+5491123456789",
      preferenciaContacto: "whatsapp",
    },
    pistas: [
      {
        id: "pista-002",
        publicacionId: "pub-004",
        autorNombre: "Ana Pérez",
        mensaje: "¡Lo encontré! Estaba en la veterinaria de Mendoza al 2000. Ya contacté al dueño.",
        fecha: "2026-05-12T11:30:00",
      },
    ],
  },
  {
    id: "pub-005",
    tipo: "perdido",
    estado: "perdido",
    perro: {
      nombre: "Maca",
      raza: "Yorkshire Terrier",
      color: "Marrón",
      tamano: "pequeno",
      sexo: "hembra",
      edadAproximada: "8 años",
      descripcion: "Es mayor y tiene problemas de visión. Necesita medicación diaria.",
      caracteristicasUnicas: "Sweater rosa tejido",
    },
    ubicacion: {
      lat: -34.6033,
      lng: -58.3817,
      barrio: "San Nicolás",
      direccionAproximada: "Microcentro, Florida y Lavalle",
    },
    fechaEvento: "2026-05-21",
    fechaPublicacion: "2026-05-21T11:00:00",
    fotos: ["https://images.unsplash.com/photo-1591946614720-90a587da4a36?w=600"],
    contacto: {
      nombre: "Patricia Suárez",
      telefono: "+5491112345678",
      email: "patricia.s@example.com",
      preferenciaContacto: "whatsapp",
    },
    recompensa: 80000,
    pistas: [],
  },
  {
    id: "pub-006",
    tipo: "encontrado",
    estado: "perdido",
    perro: {
      raza: "Bulldog Francés",
      color: "Negro",
      tamano: "pequeno",
      sexo: "hembra",
      descripcion: "La encontramos en el parque, muy nerviosa. Sin collar. Está bien cuidada.",
    },
    ubicacion: {
      lat: -34.5675,
      lng: -58.4376,
      barrio: "Belgrano",
      direccionAproximada: "Barrancas de Belgrano",
    },
    fechaEvento: "2026-05-22",
    fechaPublicacion: "2026-05-22T08:00:00",
    fotos: ["https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=600"],
    contacto: {
      nombre: "Federico Álvarez",
      telefono: "+5491101234567",
      preferenciaContacto: "whatsapp",
    },
    pistas: [],
  },
  {
    id: "pub-007",
    tipo: "perdido",
    estado: "perdido",
    perro: {
      nombre: "Bruno",
      raza: "Pastor Alemán",
      color: "Bicolor",
      tamano: "grande",
      sexo: "macho",
      edadAproximada: "4 años",
      descripcion: "Es muy obediente y conoce comandos. Tiene microchip.",
      caracteristicasUnicas: "Collar negro de cuero con tachas",
    },
    ubicacion: {
      lat: -34.6420,
      lng: -58.3736,
      barrio: "La Boca",
      direccionAproximada: "Caminito",
    },
    fechaEvento: "2026-05-18",
    fechaPublicacion: "2026-05-18T20:00:00",
    fotos: ["https://images.unsplash.com/photo-1568572933382-74d440642117?w=600"],
    contacto: {
      nombre: "Jorge Acosta",
      telefono: "+5491198765432",
      preferenciaContacto: "telefono",
    },
    recompensa: 100000,
    pistas: [],
  },
  {
    id: "pub-008",
    tipo: "perdido",
    estado: "perdido",
    perro: {
      nombre: "Coco",
      raza: "Schnauzer",
      color: "Gris",
      tamano: "mediano",
      sexo: "macho",
      edadAproximada: "6 años",
      descripcion: "Recién bañado y peluqueado. Responde a su nombre.",
    },
    ubicacion: {
      lat: -34.5985,
      lng: -58.4382,
      barrio: "Villa Crespo",
      direccionAproximada: "Av. Corrientes y Scalabrini Ortiz",
    },
    fechaEvento: "2026-05-21",
    fechaPublicacion: "2026-05-21T17:45:00",
    fotos: ["https://images.unsplash.com/photo-1605568427561-40dd23c2acea?w=600"],
    contacto: {
      nombre: "Sofía Bertolini",
      telefono: "+5491187654321",
      email: "sofia.b@example.com",
      preferenciaContacto: "email",
    },
    pistas: [],
  },
];

export function getPublicacionPorId(id: string): Publicacion | undefined {
  return PUBLICACIONES_MOCK.find((p) => p.id === id);
}
